# ═══════════════════════════════════════════════════════════════════
#  SENTINEL V5.5 — SOVEREIGN SHARDING IaC
#  Provisions physically isolated Cloud SQL shards for Tier 1 Tenants.
#  Optimized for Post-Quantum (PQ) Lattice Cryptography (Dilithium ML-DSA-65).
#
#  Architecture:
#    Governance Hub (existing) → shard_map → Tier 1 Spoke DBs (this file)
#
#  Each Tier 1 Enterprise client gets a dedicated Cloud SQL Postgres 15
#  instance with:
#    - 4 vCPU / 15GB RAM (WASM-accelerated Dilithium computation)
#    - Regional HA (multi-zone, zero-downtime failover)
#    - Private IP only (VPC-peered, no public endpoint)
#    - PITR with 7-day log retention (monotonic audit protection)
#    - SSD disk with auto-resize to 500GB cap
#    - IAM-based authentication (no password rotation needed)
#    - Deletion protection (non-negotiable for production)
#
#  Usage:
#    terraform plan -var-file="tenants.tfvars"
#    terraform apply -var-file="tenants.tfvars"
#
#  WARNING: deletion_protection = true. You MUST manually disable it
#  in the console before `terraform destroy` will succeed. This is
#  intentional — it prevents agent hallucinations from nuking prod data.
# ═══════════════════════════════════════════════════════════════════

terraform {
  required_version = ">= 1.5"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0"
    }
  }
}

# ─────────────────────────────────────────────────────
#  TIER 1 SHARD INSTANCES — Physically Isolated
# ─────────────────────────────────────────────────────

resource "google_sql_database_instance" "tenant_shard" {
  for_each = var.tier_1_tenants

  name             = "sentinel-shard-${each.key}"
  database_version = "POSTGRES_15"
  region           = var.region
  project          = var.project_id

  settings {
    # UPGRADED: 4 vCPU / 15GB RAM required for WASM-accelerated Dilithium computation.
    # 2-core machines are insufficient for Tier 1 SLA under PQ-Lattice signing load.
    tier = "db-custom-4-15360"

    # Tier 1: Regional HA with automatic failover (multi-zone)
    availability_type = "REGIONAL"

    disk_type             = "PD_SSD"
    disk_size             = 50    # Starting size for PQ-bloated evidence logs
    disk_autoresize       = true  # CRITICAL: Prevents 2 AM Disk-Full Lockouts
    disk_autoresize_limit = 500   # Cap to prevent run-away logging costs

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      transaction_log_retention_days = 7  # Monotonic Audit Protection
    }

    ip_configuration {
      ipv4_enabled    = false           # No public IP — private VPC only
      private_network = var.vpc_id

      # PgBouncer is deployed as a sidecar container in k8s-sidecar.yaml.
      # It connects to this instance's private IP on port 5432 and exposes
      # port 6432 for the Veritas Proxy / Hub. Transaction pooling mode
      # with DEFAULT_POOL_SIZE=120 and MAX_CLIENT_CONN=10,000 prevents
      # connection exhaustion under 5,000 VU load.
    }

    # Cloud SQL max_connections: Explicit cap to match PgBouncer pool.
    # Default for db-custom-4-15360 is ~200, but we enforce 150 to leave
    # headroom for maintenance connections (replication, backups).
    database_flags {
      name  = "max_connections"
      value = "150"
    }

    # Connection logging: Required for forensic audit of pool behavior.
    database_flags {
      name  = "log_connections"
      value = "on"
    }
    database_flags {
      name  = "log_disconnections"
      value = "on"
    }

    # Enterprise-Grade Security
    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    insights_config {
      query_insights_enabled  = true
      record_application_tags = true
    }
  }

  # THE SOVEREIGN GATE: Prevents agentic 'terraform destroy' hallucinations
  deletion_protection = true
}


# ─────────────────────────────────────────────────────
#  SHARD DATABASES — One per tenant instance
# ─────────────────────────────────────────────────────

resource "google_sql_database" "tenant_db" {
  for_each = google_sql_database_instance.tenant_shard

  name      = "sentinel_sovereign_db"
  instance  = each.value.name
  project   = var.project_id
  charset   = "UTF8"
  collation = "en_US.UTF8"
}


# ─────────────────────────────────────────────────────
#  SECRET MANAGEMENT — Secure Shard DSN Storage
#  Values stored here MUST be AES-256-GCM ciphertext
#  generated by SecurityManager.encryptField().
# ─────────────────────────────────────────────────────

resource "google_secret_manager_secret" "shard_dsn" {
  for_each  = var.tier_1_tenants
  secret_id = "sentinel-dsn-${each.key}"
  project   = var.project_id

  replication {
    auto {}
  }

  labels = {
    sentinel_tier = "1"
    tenant        = each.key
    managed_by    = "terraform"
  }
}


# ─────────────────────────────────────────────────────
#  OUTPUTS — For Governance Hub shard_map population
# ─────────────────────────────────────────────────────

output "shard_map_entries" {
  description = "Metadata required to populate the Sentinel Governance Hub shard_map table."
  value = {
    for k, v in google_sql_database_instance.tenant_shard : k => {
      connection_name = v.connection_name
      private_ip      = v.private_ip_address
      project_tier    = "TIER_1_ENTERPRISE"
    }
  }
}
